### ISSUE TITLE
Select Professors

### ISSUE THREAD

**Issue by kevinatorchen** [kevinatorchen/CoursePlanner#2]
Allow users to select which professors they would like to have the class with.

Front end: When selecting a class, choose from a list of professors. By default, have all of them selected to indicate that the student is fine with taking the course from any professor.

Back end: planCourses() should now take in a list of CourseRequest objects containing both the Course and the professor, instead of just a list of courses. More filtering needs to be done when dynamically creating all possible schedules.

**Comment by myothiha09** [comment]
I can use the search function I created for searching classes to filter from all the possible schedules for this function.  
 - to ignore a section if this professor.
 - to take a section if only this professor.

Instead of adding it to the request, I think we can just allow the user to filter in schedule screen. I will need to think of a good way to do it though.

**Comment by kevinatorchen** [comment]
I feel doing the first one (ignore a section if it is this professor) would not be an idea that GT administrators would encourage. What I think should be done is that the student selects the professors that he/she wants to take it with.

I think the best way to achieve this for front-end is to add another dialog box when adding a class. So as of now, we have a dialog box to select the course abbreviation (e.g. PHYS, APPH), and then we have a dialog box to select the course number (e.g. PHYS 2211 or APPH 1040). Now I recommend you to add a third dialog box to select which professors the student would like to take the course with. Be sure to allow multiple professors to be selected (and by default, they should all be selected).

I feel this is the most intuitive approach.

**Comment by kevinatorchen** [comment]
As discussed, the second dialog box (course number) should contain an "add class" button to skip the remaining dialog boxes. Additionally, the last dialog box (professors) should have all professors checked by default.

**Comment by kevinatorchen** [comment]
@myothiha09,
I have implemented the Back End for this to be done. See the "TODO" sections of the controller classes to see what sections of the existing code need to be changed.
