### ISSUE TITLE
Course Long Name

### ISSUE THREAD

**Issue by myothiha09** [kevinatorchen/CoursePlanner#5]
The courses should also hold long name.
For example. CS 1331 - Intro to Object Oriented Programming.
Currently, we are not holding Intro to Object Oriented Programming.

**Comment by kevinatorchen** [comment]
I will add an attribute to the Course.java class.

**Comment by kevinatorchen** [comment]
Hey @myothiha09 , it looks like there now is a longName attribute in Course.java, so did you finish this issue? If so, please close this issue.
