### ISSUE TITLE
Change All Instances of ArrayList<Section> to Schedule

### ISSUE THREAD

**Issue by kevinatorchen** [kevinatorchen/CoursePlanner#6]
Change all instances of `ArrayList<Section>` to the class "Schedule". The reason for doing so is that I can create Comparators for an array of schedules. This is needed for ordering the search results when we want to allow the user to list the schedules in a particular order (e.g. list schedules that have fewest breaks in between first)

This has already been done back-end. This still needs to be done front end.

See the TODO item in CoursePlanner.java.

**Comment by myothiha09** [comment]
OK, noted.
